### PR TITLE
Implement and test control API

### LINKED ISSUE #2: Create controls class to let the programmer easily define controls, save controls, and load controls
Directions and preliminary functions have been created in [controls.h](https://github.com/tjunruh/ASCII_Board_Game_Engine/blob/main/Code/ascii_engine/controls.h) Define functions in [controls.cpp](https://github.com/tjunruh/ASCII_Board_Game_Engine/blob/main/Code/ascii_engine/controls.cpp).  Make necessary adjustments and add any functions to the class that are necessary.

### PR DESCRIPTION
**Pull request by MatthewMateusz**
Implemented functions defined in controls.h.

Testing was done by running each function and seeing if it did the correct actions.

The Makefile now compiles ascii_engine into a shared object; this allows for a simple compilation check for the library. We might want to change this to something else in the future, it just for compilation test.

If trouble merging, contact me and I will help.

This pull request closes #2

### CODE REVIEW

**Comment by MatthewMateusz** [comment]
It seems there will be trouble with merging, as some files have changed since I started development.

**Comment by MatthewMateusz** [comment]
I fixed some parity issues between Windows and Linux builds. It seems that menu::set_output is not defined as a function and is missing an implementation. I'll wait until you can comment about this before continuing.

**Comment by MatthewMateusz** [comment]
Also closes #2

**Comment by MatthewMateusz** [comment]
@tjunruh Brought in fix from upstream. All targets compile.

**Comment by tjunruh** [comment]
Changes look good. I was able to compile on Windows by placing the json.hpp file in the directory where Visual Studio Code 2019 holds its system header files.

**Pull request merged**
